- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.mohansaivenna.cloud
  vars_prompt: #by putting we are securing password not to show in the code
  - name: mysql_root_password
    prompt: please enter MySQL root password
    private: no #im setting it no to seethe password im giving for the root passoword ; it shoud yes not show the password in the terminal
  tasks:
  - name: Install MySQL Server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: Start and Enable MySQL server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes #lookinto out output-1 why we are adding the dependencies 

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography #this used for password in commandline
      executable: pip3.9 # pip3.11 if python version is 3.11 ; in ansible version we are using python version vast 3.9.18
      # [ ec2-user@ip-172-31-29-113 ~/my-website-using-ansible ]$ ansible --version
      #   ansible [core 2.14.14]
      #     config file = /etc/ansible/ansible.cfg
      #     configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
      #     ansible python module location = /usr/lib/python3.9/site-packages/ansible
      #     ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
      #     executable location = /usr/bin/ansible
      #     python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
      #     jinja version = 3.1.2
      #     libyaml = True

  # check password is already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version # this is used for checking the version
    ignore_errors: yes
    register: mysql_connection_output #register is used to get the output of the command we are using

  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{mysql_connection_output}} " 
      # check output-2 why we have written the stepup root password

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true # don't give {{ }} in when condition 
    #by using the when condition from the output - msg: "Output: {{mysql_connection_output}} " we are saying when its true run this command; if it fails
    #this command will not run
    #check output-3 for the successful setting up root password
    #check output-4 for the ignoring the root password running the same command again.
  
  # validating the sql port is # check output: 5
  - name: Checking the SQL port
    ansible.builtin.command: "netstat -lntp | grep 3306"
    register: netstat_output

  - name: Print netstat output
    ansible.builtin.debug:
      msg: "Output: {{ netstat_output.stdout_lines }}"

  #validating the MySQL login and show databases
  - name: MySQL login and show databases
    community.mysql.mysql_query:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      query: 'SHOW DATABASES;'
    register: mysql_showdatabases_output
    ignore_errors: yes
  
  - name: Print Showdatabase output
    ansible.builtin.debug:
      msg: "Output: {{ mysql_showdatabases_output }}"


#We have received an error 1st time when we run it saying that 
#"msg": "A MySQL module is required: for Python 2.7 either PyMySQL, or MySQL-python, or for Python 3.X mysqlclient or PyMySQL.
  # Ansible is developed in python ;
  # now we are connecting to mysql from ansible which is developed in python;
  # PyMySQL is a dependency for python to connect mysql servers
  # pip --> this is for installing python dependencies
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html


# output-1

#   [ ec2-user@ip-172-31-29-113 ~/my-website-using-ansible ]$ ansible-playbook -i inventory -e ansible_user=ec2-user -e ansible_password=DevOps321 database.yaml

#   PLAY [configure DB server] ********************************************************************************************************************************************************************

#   TASK [Gathering Facts] ************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Install MySQL Server] *******************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Start and Enable MySQL server] **********************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [check DB connection] ********************************************************************************************************************************************************************
#   fatal: [db.mohansaivenna.cloud]: FAILED! => {"changed": false, "msg": "A MySQL module is required: for Python 2.7 either PyMySQL, or MySQL-python, or for Python 3.X mysqlclient or PyMySQL. Consider setting ansible_python_interpreter to use the intended Python version."}
#   ...ignoring

#   TASK [print output] ***************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud] => {
#       "msg": "Output: {'failed': True, 'msg': 'A MySQL module is required: for Python 2.7 either PyMySQL, or MySQL-python, or for Python 3.X mysqlclient or PyMySQL. Consider setting ansible_python_interpreter to use the intended Python version.', 'changed': False} "
#   }

#   PLAY RECAP ************************************************************************************************************************************************************************************
#   db.mohansaivenna.cloud     : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1

#Error in output-2  ; 
# "msg": "unable to connect to database using pymysql 1.1.1, we have setup the setup root password

# output-2

#   [ ec2-user@ip-172-31-29-113 ~/my-website-using-ansible ]$ ansible-playbook -i inventory -e ansible_user=ec2-user -e ansible_password=DevOps321 database.yaml

#   PLAY [configure DB server] ********************************************************************************************************************************************************************

#   TASK [Gathering Facts] ************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Install MySQL Server] *******************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Start and Enable MySQL server] **********************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [install python mysql dependencies] ******************************************************************************************************************************************************
#   changed: [db.mohansaivenna.cloud]

#   TASK [check DB connection] ********************************************************************************************************************************************************************
#   fatal: [db.mohansaivenna.cloud]: FAILED! => {"changed": false, "msg": "unable to connect to database using pymysql 1.1.1, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1130, \"Host 'ip-172-31-82-168.ec2.internal' is not allowed to connect to this MySQL server\")"}
#   ...ignoring

#   TASK [print output] ***************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud] => {
#       "msg": "Output: {'failed': True, 'msg': 'unable to connect to database using pymysql 1.1.1, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1130, \"Host \\'ip-172-31-82-168.ec2.internal\\' is not allowed to connect to this MySQL server\")', 'changed': False} "
#   }

#   PLAY RECAP ************************************************************************************************************************************************************************************
#   db.mohansaivenna.cloud     : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1 

# output-3

#   [ ec2-user@ip-172-31-29-113 ~/my-website-using-ansible ]$ ansible-playbook -i inventory -e ansible_user=ec2-user -e ansible_password=DevOps321 database.yaml
#   please enter MySQL root password: ExpenseApp@1

#   PLAY [configure DB server] ********************************************************************************************************************************************************************

#   TASK [Gathering Facts] ************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Install MySQL Server] *******************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Start and Enable MySQL server] **********************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [install python mysql dependencies] ******************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [check DB connection] ********************************************************************************************************************************************************************
#   fatal: [db.mohansaivenna.cloud]: FAILED! => {"changed": false, "msg": "unable to connect to database using pymysql 1.1.1, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1130, \"Host 'ip-172-31-82-168.ec2.internal' is not allowed to connect to this MySQL server\")"}
#   ...ignoring

#   TASK [print output] ***************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud] => {
#       "msg": "Output: {'failed': True, 'msg': 'unable to connect to database using pymysql 1.1.1, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1130, \"Host \\'ip-172-31-82-168.ec2.internal\\' is not allowed to connect to this MySQL server\")', 'changed': False} "
#   }

#   TASK [setup root password] ********************************************************************************************************************************************************************
#   changed: [db.mohansaivenna.cloud]

#   PLAY RECAP ************************************************************************************************************************************************************************************
#   db.mohansaivenna.cloud     : ok=7    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   

# output-4:
#   [ ec2-user@ip-172-31-29-113 ~/my-website-using-ansible ]$ ansible-playbook -i inventory -e ansible_user=ec2-user -e ansible_password=DevOps321 database.yaml
#   please enter MySQL root password: ExpenseApp@1

#   PLAY [configure DB server] ********************************************************************************************************************************************************************

#   TASK [Gathering Facts] ************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Install MySQL Server] *******************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Start and Enable MySQL server] **********************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [install python mysql dependencies] ******************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [check DB connection] ********************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [print output] ***************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud] => {
#       "msg": "Output: {'changed': False, 'connector_name': 'pymysql', 'connector_version': '1.1.1', 'version': {'major': 8, 'minor': 0, 'release': 36, 'suffix': '', 'full': '8.0.36'}, 'failed': False} "
#   }

#   TASK [setup root password] ********************************************************************************************************************************************************************
#   skipping: [db.mohansaivenna.cloud]

#   PLAY RECAP ************************************************************************************************************************************************************************************
#   db.mohansaivenna.cloud     : ok=6    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

# output-5:

#   [ ec2-user@ip-172-31-38-25 ~/my-website-using-ansible ]$ ansible-playbook -i inventory -e ansible_user=ec2-user -e ansible_password=DevOps321 database.yaml
#   please enter MySQL root password: ExpenseApp@1

#   PLAY [configure DB server] ********************************************************************************************************************************************************************

#   TASK [Gathering Facts] ************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Install MySQL Server] *******************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Start and Enable MySQL server] **********************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [install python mysql dependencies] ******************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [check DB connection] ********************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [print output] ***************************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud] => {
#       "msg": "Output: {'changed': False, 'connector_name': 'pymysql', 'connector_version': '1.1.1', 'version': {'major': 8, 'minor': 0, 'release': 36, 'suffix': '', 'full': '8.0.36'}, 'failed': False} "
#   }

#   TASK [setup root password] ********************************************************************************************************************************************************************
#   skipping: [db.mohansaivenna.cloud]

#   TASK [Checking the SQL port] ******************************************************************************************************************************************************************
#   changed: [db.mohansaivenna.cloud]

#   TASK [Print netstat output] *******************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud] => {
#       "msg": "Output: ['Active Internet connections (only servers)', 'Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    ', 'tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1247/sshd: /usr/sbi ', 'tcp6       0      0 :::3306                 :::*                    LISTEN      2453/mysqld         ', 'tcp6       0      0 :::22                   :::*                    LISTEN      1247/sshd: /usr/sbi ', 'tcp6       0      0 :::33060                :::*                    LISTEN      2453/mysqld         ']"
#   }

#   TASK [MySQL login and show databases] *********************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud]

#   TASK [Print Showdatabase output] **************************************************************************************************************************************************************
#   ok: [db.mohansaivenna.cloud] => {
#       "msg": "Output: [[{'Database': 'information_schema'}, {'Database': 'mysql'}, {'Database': 'performance_schema'}, {'Database': 'sys'}]]"
#   }

#   PLAY RECAP ************************************************************************************************************************************************************************************
#   db.mohansaivenna.cloud     : ok=10   changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   